tasks/task08/epublication/config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :people
  resources :faculties
  root to: 'publications#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

tasks/task08/epublication/app/models/person.rb
# Model represents persons
class Person < ApplicationRecord
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i.freeze

  belongs_to :faculty
  has_many :publications

  validates :fullname, :username, :faculty_id, presence: true
  validates :username, :email, uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX }

  # Returns the fullname with the email in the format "fullname <email>"
  #
  # @return [String]
  def name_email
    "#{fullname} <#{email}>"
  end
end

tasks/task08/epublication/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:fullname, :email, :username, :faculty_id)
  end
end

tasks/task08/epublication/app/helpers/people_helper.rb
# Helper for people views
module PeopleHelper
  def selectable_faculties
    Faculty.all.map { |f| [f.name, f.id] }
  end
end

tasks/task08/epublication/app/views/people/_form.html.erb
<%= form_with(model: person, local: true, html: { autocomplete: "off" }) do |form| %>

  <div class="form-group">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, class: 'form-control', placeholder: 'Enter fullname', required: true %>
    <div class="error text-danger">
      <%= inline_errors(person, :fullname) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Enter email', required: true, type: 'email' %>
    <div class="error text-danger">
      <%= inline_errors(person, :email) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control', placeholder: 'Enter username', required: true %>
    <div class="error text-danger">
      <%= inline_errors(person, :username) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :faculty_id %>
    <%= form.select :faculty_id, selectable_faculties, {}, {class: 'form-control'} %>
    <div class="error text-danger">
      <%= inline_errors(person, :faculty_id) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

tasks/task08/epublication/app/views/people/edit.html.erb
<h2>Editing Person</h2>

<%= render 'form', person: @person %>

<%= link_to @person do %>
  <button class="btn btn-primary">Show</button>
<% end %>

<%= link_to people_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>

tasks/task08/epublication/app/views/people/index.html.erb
<h2>People</h2>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Fullname</th>
      <th scope="col">Email</th>
      <th scope="col">Username</th>
      <th scope="col">Faculty</th>
      <th scope="col">Publications</th>
      <th scope="col" style="width: 180px">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.fullname %></td>
        <td><%= person.email %></td>
        <td><%= person.username %></td>
        <td><%= person.faculty.name %></td>
        <td><%= person.publications.count %></td>


        <td class="action-col"  style="text-align: right">
          <%= link_to person do %>
            <button title="Show" class="btn btn-primary"><%= fa_icon "eye" %></button>
          <% end %>
          <%= link_to edit_person_path(person) do %>
            <button title="Edit" class="btn btn-success"><%= fa_icon "edit" %></button>
          <% end %>
          <%= link_to person, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button title="Delete" class="btn btn-danger"><%= fa_icon "trash" %></button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_person_path do %>
  <button class="btn btn-primary">New Person</button>
<% end %>

tasks/task08/epublication/app/views/people/new.html.erb
<h2>New Person</h2>

<%= render 'form', person: @person %>

<%= link_to people_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>

tasks/task08/epublication/app/views/people/show.html.erb
<h2>Person detail</h2>

<table class="table table-bordered table-detail">
  <tbody>
  <tr>
    <td><strong>Fullname</strong></td>
    <td><%= @person.fullname %></td>
  </tr>

  <tr>
    <td><strong>Email</strong></td>
    <td><%= @person.email %></td>
  </tr>

  <tr>
    <td><strong>Username</strong></td>
    <td><%= @person.username %></td>
  </tr>

  <tr>
    <td><strong>Faculty</strong></td>
    <td>
      <%= @person.faculty.name %>
      <%= link_to @person.faculty, target: "_blank" do %>
        <%= fa_icon "eye" %>
      <% end %>
    </td>
  </tr>

  <tr>
    <td><strong>Publications</strong></td>
    <td>
      <% if @person.publications.empty? %>
        None
      <% else %>
        <ul>
          <% @person.publications.each do |publication| %>
            <li>
              <%= publication.name %>
              <%= link_to publication, target: "_blank" do %>
                <%= fa_icon "eye" %>
              <% end %>
            </li>
          <% end %>

        </ul>
        <%#= @person.faculty.name %>
        <%#= link_to @person.faculty, target: "_blank" do %>
        <%#= fa_icon "eye" %>
        <%# end %>
      <% end %>
    </td>
  </tr>
  </tbody>
</table>

<%= link_to edit_person_path(@person) do %>
  <button class="btn btn-success">Edit</button>
<% end %>

<%= link_to people_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>