tasks/task08/epublication/config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :people
  resources :faculties
  root to: 'publications#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

tasks/task08/epublication/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= root_path %>">ePublication</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= faculties_path %>">Faculties<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<%= people_path %>">People</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= publications_path %>">Publications</a>
      </li>
    </ul>
  </div>
</nav>

tasks/task08/epublication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Epublication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% unless notice.nil? %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end  %>
    <%= yield %>
  </div>
  </body>
</html>