final_work/config/routes.rb
Rails.application.routes.draw do
  get 'follow/follow'
  get 'follow/unfollow'

  get 'activities/user', to: 'activities#user_activities', as: 'user_activities'

  get 'activities/:id/points', to: 'activities#activity_points', as: 'activity_points'
  put 'activities/:id/kudos', to: 'kudos#give_kudos', as: 'give_kudos'
  resources :activities do
    resources :comments
  end

  devise_for :users
  root to: "welcome#home"

  get '/users', to: 'users#index'
  get '/profile/:id', to: 'users#profile', as: 'user_profile'
  get '/dashboard', to: 'dashboard#index'
  put '/follow/:id', to: 'follow#follow', as: 'follow_user'
  put '/unfollow/:id', to: 'follow#unfollow', as: 'unfollow_user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

final_work/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= user_signed_in? ? dashboard_path : root_path %>">SportSocial</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link" href="/dashboard">Dashboard <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= users_path %>">Users</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Activities
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= user_activities_path %>">My activities</a>
            <a class="dropdown-item" href="<%= activities_path %>">All activities</a>
          </div>
        </li>
      <% end %>
    </ul>
    <div>
      <% if user_signed_in? %>
        <%= link_to new_activity_path do %>
          <button class="btn btn-success">Upload activity</button>
        <% end %>
        <%= link_to user_profile_path(current_user) do %>
          <button class="btn btn-outline-info"><%= "#{current_user.first_name}'s profile" %></button>
        <% end %>

        <%= link_to destroy_user_session_path, method: :delete do %>
          <button class="btn btn-outline-info">Sign out</button>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <button class="btn btn-outline-info">Sign in</button>
        <% end %>

        <%= link_to new_user_registration_path do %>
          <button class="btn btn-outline-info">Sign up</button>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

final_work/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FinalWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://api.mapbox.com/mapbox-gl-js/v1.7.0/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.7.0/mapbox-gl.css" rel="stylesheet" />

  </head>

  <body>
  <script>
      mapboxgl.accessToken = 'pk.eyJ1Ijoic2Vib3RhcyIsImEiOiJjaWwzdmtvaXQwMGNreDFtMDM3eDByNmRiIn0.rbG7sJZTWCiqssnDEcZZXg';
  </script>
  <%= render "layouts/navbar" %>

  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
      <%= value %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>