tasks/task08/epublication/config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :people
  resources :faculties
  root to: 'publications#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

tasks/task08/epublication/app/models/publication.rb
# Model represents publications
class Publication < ApplicationRecord
  belongs_to :person
  validates :name, :person_id, presence: true

  # Returns the publication's faculty.
  # The faculty is found according to the owner of the publication.
  #
  # @return [Faculty]
  def faculty
    person.faculty
  end

  # Is the publication published?
  # If the date is nil => not published yet
  # If the date is not nil => published
  #
  # @return [Boolean]
  def published?
    !published_at.blank?
  end
end

tasks/task08/epublication/app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show; end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit; end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def publication_params
    params.require(:publication).permit(:name, :published_at, :abstract, :person_id)
  end
end

tasks/task08/epublication/app/helpers/publications_helper.rb
# Helper for publications views
module PublicationsHelper
  def selectable_people
    Person.all.map { |f| [f.name_email, f.id] }
  end

  def icon_published(published)
    icon_type = 'times-circle'
    class_name = 'not-published'

    if published
      icon_type = 'check-circle'
      class_name = 'published'
    end

    fa_icon(icon_type, class: "#{class_name} fa-2x")
  end

  def published_date_or_not(published_at)
    published_at.nil? ? 'Not yet' : human_date(published_at)
  end
end

tasks/task08/epublication/app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true, html: { autocomplete: "off" }) do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name', required: true %>
    <div class="error text-danger">
      <%= inline_errors(publication, :name) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :published_at %>
    <%= form.text_field :published_at, class: 'form-control datepicker', placeholder: 'Enter date e.g. 22.11.2019',
                        value: human_date(form.object.published_at) %>
    <div class="error text-danger">
      <%= inline_errors(publication, :published_at) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :abstract %>
    <%= form.text_area :abstract, class: 'form-control', placeholder: 'Enter abstract' %>
    <div class="error text-danger">
      <%= inline_errors(publication, :abstract) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :person_id %>
    <%= form.select :person_id, selectable_people, {}, {class: 'form-control'} %>
    <div class="error text-danger">
      <%= inline_errors(publication, :person_id) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-success' %>
  </div>

  <script type="text/javascript">
      $(document).ready(function(){
          $('.datepicker').datepicker({
              showButtonPanel: true,
              changeMonth: true,
              changeYear: true,
              dateFormat: 'dd.mm.yy'
          });
      });
  </script>


<% end %>

tasks/task08/epublication/app/views/publications/edit.html.erb
<h2>Editing Publication</h2>

<%= render 'form', publication: @publication %>

<%= link_to @publication do %>
  <button class="btn btn-primary">Show</button>
<% end %>

<%= link_to publications_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>

tasks/task08/epublication/app/views/publications/index.html.erb
<h2>Publications</h2>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col" style="width: 100px">Published</th>
      <th scope="col">Person</th>
      <th scope="col" style="width: 180px">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.name %></td>
        <td><%= icon_published(publication.published?) %></td>
        <td><%= publication.person.name_email %></td>
        <td class="action-col"  style="text-align: right">
          <%= link_to publication do %>
            <button title="Show" class="btn btn-primary"><%= fa_icon "eye" %></button>
          <% end %>
          <%= link_to edit_publication_path(publication) do %>
            <button title="Edit" class="btn btn-success"><%= fa_icon "edit" %></button>
          <% end %>
          <%= link_to publication, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button title="Delete" class="btn btn-danger"><%= fa_icon "trash" %></button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_publication_path do %>
  <button class="btn btn-primary">New Publication</button>
<% end %>

tasks/task08/epublication/app/views/publications/new.html.erb
<h2>New Publication</h2>

<%= render 'form', publication: @publication %>

<%= link_to publications_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>

tasks/task08/epublication/app/views/publications/show.html.erb
<h2>Publication detail</h2>

<table class="table table-bordered table-detail">
  <tbody>
  <tr>
    <td><strong>Name</strong></td>
    <td><%= @publication.name %></td>
  </tr>

  <tr>
    <td><strong>Abstract</strong></td>
    <td><%= @publication.abstract %></td>
  </tr>

  <tr>
    <td><strong>Published at</strong></td>
    <td><%= published_date_or_not(@publication.published_at) %></td>
  </tr>

  <tr>
    <td><strong>Person</strong></td>
    <td>
      <%= @publication.person.name_email %>
      <%= link_to @publication.person, target: "_blank" do %>
        <%= fa_icon "eye" %>
      <% end %>
    </td>
  </tr>

  <tr>
    <td><strong>Faculty</strong></td>
    <td>
      <%= @publication.faculty.name %>
      <%= link_to @publication.faculty, target: "_blank" do %>
        <%= fa_icon "eye" %>
      <% end %>
    </td>
  </tr>
  </tbody>
</table>

<%= link_to edit_publication_path(@publication) do %>
  <button class="btn btn-success">Edit</button>
<% end %>

<%= link_to publications_path do %>
  <button class="btn btn-secondary">Back</button>
<% end %>